server:
  port: 8083

spring:
  application:
    name: assessment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Hanusuman11!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379

groq:
  api:
    key: ${GROQ_API_KEY:default}
    url: https://api.groq.com/openai/v1/chat/completions
