server:
  port: 8082

spring:
  application:
    name: batch-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Hanusuman11!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
